# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "PersonMessage" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :email, :string, 3
  end
end

PersonMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("PersonMessage").msgclass
